const actionKeys = {
  CART_ITEM_ADD: 'CART_ITEM_ADD',
  CART_ITEM_REMOVE: 'CART_ITEM_REMOVE',
  CART_CLEAR: 'CART_CLEAR',
  CART_LOAD: 'CART_LOAD',
  CART_SAVE: 'CART_SAVE',

  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
};


export default actionKeys;
